all_of_us_vcf: acaf_threshold.chr{chr}.vcf.bgz #must be hg38, phased and indexed. Should contain "chr" wildcards
dataset: AOU # set to "test" to test pipeline on 1KGP-ACB and 1KGP-ASW or AOU to analyze All of Us data. Otherwise it is assumed that target vcf is provided
related_samples: data/related_individuals.txt
ldlink_token: <your_token>

# Download links for 1KG and human reference genome
phase3_1KG_base_url: ftp://ftp.1000genomes.ebi.ac.uk/vol1/ftp/release/20130502/
hgdp_wgs_url: ftp://ngs.sanger.ac.uk/production/hgdp/hgdp_wgs.20190516/hgdp_wgs.20190516.full.chr{chr}.vcf.gz
accessible_genome_mask_url: http://ftp.1000genomes.ebi.ac.uk/vol1/ftp/release/20130502/supporting/accessible_genome_masks/20141020.strict_mask.whole_genome.bed
segmental_duplications_url: https://hgdownload.soe.ucsc.edu/goldenPath/hg38/database/genomicSuperDups.txt.gz
reference_gap_url: https://hgdownload.soe.ucsc.edu/goldenPath/hg38/database/gap.txt.gz
simple_repeat_map_url: http://hgdownload.soe.ucsc.edu/goldenPath/hg38/database/simpleRepeat.txt.gz
hg38_chrom_sizes_url: http://hgdownload.cse.ucsc.edu/goldenpath/hg38/bigZips/hg38.chrom.sizes
hg38_fasta_url: http://hgdownload.cse.ucsc.edu/goldenpath/hg38/bigZips/hg38.fa.gz
string_url: https://stringdb-static.org/download/protein.links.v11.5/9606.protein.links.v11.5.txt.gz
gwas_catalog_url: https://www.ebi.ac.uk/gwas/api/search/downloads/alternative
gwas_efo_trait_mapping_url: https://www.ebi.ac.uk/gwas/api/search/downloads/trait_mappings
dbSNP_url: https://hgdownload.soe.ucsc.edu/gbdb/hg38/snp/dbSnp155Common.bb
whole_genome_alignments_url: https://hgdownload.soe.ucsc.edu/goldenPath/hg38/vs{species_upper}/hg38.{species}.net.axt.gz
# whole_genome_alignments_url: https://hgdownload.soe.ucsc.edu/goldenPath/hg19/vs{species_upper}/syntenicNet/chr{chr}.hg19.{species}.synNet.axt.gz
# Link for downloading Heng Li's seqbility
seqbility_url: http://lh3lh3.users.sourceforge.net/download/seqbility-20091110.tar.bz2
beagle_url: https://faculty.washington.edu/browning/beagle/beagle.22Jul22.46e.jar
hapmap_genetic_map_plink_url: https://bochet.gcc.biostat.washington.edu/beagle/genetic_maps/plink.GRCh38.map.zip
hapmap_genetic_map_url: https://stdpopsim.s3.us-west-2.amazonaws.com/genetic_maps/HomSap/HapMapII_GRCh38.tar.gz
hg19_to_hg38_chain_url: http://hgdownload.soe.ucsc.edu/goldenPath/hg19/liftOver/hg19ToHg38.over.chain.gz
hg38_to_hg19_chain_url: http://hgdownload.soe.ucsc.edu/goldenPath/hg38/liftOver/hg38ToHg19.over.chain.gz

hg38_cytobands_url: http://hgdownload.cse.ucsc.edu/goldenpath/hg38/database/cytoBand.txt.gz
# Annotations
knownGene_url: https://hgdownload.soe.ucsc.edu/goldenPath/hg38/database/knownGene.txt.gz
knownToEnsembl_url: https://hgdownload.soe.ucsc.edu/goldenPath/hg38/database/knownToEnsembl.txt.gz
ensembl_uniprot_url: https://ftp.ensembl.org/pub/release-109/tsv/homo_sapiens/Homo_sapiens.GRCh38.109.uniprot.tsv.gz
gerp_url: https://hgdownload.soe.ucsc.edu/gbdb/hg38/dbNsfp/dbNsfpGerpRs.bw
phastCons_url: http://hgdownload.soe.ucsc.edu/goldenPath/hg38/database/phastCons100way.txt.gz
phyloP_url: http://hgdownload.soe.ucsc.edu/goldenPath/hg38/database/phyloP100way.txt.gz
recomb_rate_url: http://hgdownload.soe.ucsc.edu/gbdb/hg38/recombRate/recombAvg.bw
bstat_url: https://www.dropbox.com/sh/93jeh51ezz0xkyz/AAB0ss_tlZ1AeCrfwQyfoiV3a/hg38/hg19/bstat_hg19.txt?dl=0 # from Priya Moorjani
gnomad_url: https://hgdownload.soe.ucsc.edu/gbdb/hg38/gnomAD/vcf/gnomad.genomes.r3.0.sites.vcf.gz
clinvar_url: https://ftp.ncbi.nlm.nih.gov/pub/clinvar/vcf_GRCh38/clinvar.vcf.gz
gtex_url: https://storage.googleapis.com/adult-gtex/bulk-qtl/v8/single-tissue-cis-qtl/GTEx_Analysis_v8_eQTL_independent.tar
# Boosting scores for selection in test in source populations
url_boosting_scores_eur_complete: https://hsb.upf.edu/hsb_data/hierarchical_boosting/selection_scan/hierarchical_boosting_CEU/whole_genome.CEU.Complete.boosting.scores
url_boosting_scores_eur_recent_complete: https://hsb.upf.edu/hsb_data/hierarchical_boosting/selection_scan/hierarchical_boosting_CEU/whole_genome.CEU.Complete.Recent.boosting.scores
url_boosting_scores_eur_ancient_complete: https://hsb.upf.edu/hsb_data/hierarchical_boosting/selection_scan/hierarchical_boosting_CEU/whole_genome.CEU.Complete.Ancient.boosting.scores
url_boosting_scores_eur_incomplete: https://hsb.upf.edu/hsb_data/hierarchical_boosting/selection_scan/hierarchical_boosting_CEU/whole_genome.CEU.Incomplete.boosting.scores
url_boosting_scores_eur_recent_incomplete: https://hsb.upf.edu/hsb_data/hierarchical_boosting/selection_scan/hierarchical_boosting_CEU/whole_genome.CEU.Incomplete.Recent.boosting.scores
url_boosting_scores_eur_ancient_incomplete: https://hsb.upf.edu/hsb_data/hierarchical_boosting/selection_scan/hierarchical_boosting_CEU/whole_genome.CEU.Incomplete.Ancient.boosting.scores
url_boosting_scores_afr_complete: https://hsb.upf.edu/hsb_data/hierarchical_boosting/selection_scan/hierarchical_boosting_YRI/whole_genome.YRI.Complete.boosting.scores
url_boosting_scores_afr_recent_complete: https://hsb.upf.edu/hsb_data/hierarchical_boosting/selection_scan/hierarchical_boosting_YRI/whole_genome.YRI.Complete.Recent.boosting.scores
url_boosting_scores_afr_ancient_complete: https://hsb.upf.edu/hsb_data/hierarchical_boosting/selection_scan/hierarchical_boosting_YRI/whole_genome.YRI.Complete.Ancient.boosting.scores
url_boosting_scores_afr_incomplete: https://hsb.upf.edu/hsb_data/hierarchical_boosting/selection_scan/hierarchical_boosting_YRI/whole_genome.YRI.Incomplete.boosting.scores
url_boosting_scores_afr_recent_incomplete: https://hsb.upf.edu/hsb_data/hierarchical_boosting/selection_scan/hierarchical_boosting_YRI/whole_genome.YRI.Incomplete.Recent.boosting.scores
url_boosting_scores_afr_ancient_incomplete: https://hsb.upf.edu/hsb_data/hierarchical_boosting/selection_scan/hierarchical_boosting_YRI/whole_genome.YRI.Incomplete.Ancient.boosting.scores
url_boosting_scores_eas_complete: https://hsb.upf.edu/hsb_data/hierarchical_boosting/selection_scan/hierarchical_boosting_CHB/whole_genome.CHB.Complete.boosting.scores
url_boosting_scores_eas_recent_complete: https://hsb.upf.edu/hsb_data/hierarchical_boosting/selection_scan/hierarchical_boosting_CHB/whole_genome.CHB.Complete.Recent.boosting.scores
url_boosting_scores_eas_ancient_complete: https://hsb.upf.edu/hsb_data/hierarchical_boosting/selection_scan/hierarchical_boosting_CHB/whole_genome.CHB.Complete.Ancient.boosting.scores
url_boosting_scores_eas_incomplete: https://hsb.upf.edu/hsb_data/hierarchical_boosting/selection_scan/hierarchical_boosting_CHB/whole_genome.CHB.Incomplete.boosting.scores
url_boosting_scores_eas_recent_incomplete: https://hsb.upf.edu/hsb_data/hierarchical_boosting/selection_scan/hierarchical_boosting_CHB/whole_genome.CHB.Incomplete.Recent.boosting.scores
url_boosting_scores_eas_ancient_incomplete: https://hsb.upf.edu/hsb_data/hierarchical_boosting/selection_scan/hierarchical_boosting_CHB/whole_genome.CHB.Incomplete.Ancient.boosting.scores
ldsc_plink_url: https://zenodo.org/record/7768714/files/1000G_Phase3_plinkfiles.tgz
ldsc_freq_url: https://zenodo.org/record/7768714/files/1000G_Phase3_frq.tgz
ldsc_weights_url: https://zenodo.org/record/7768714/files/1000G_Phase3_weights_hm3_no_MHC.tgz
ldsc_baseline_model_url: https://zenodo.org/record/8292725/files/1000G_Phase3_baselineLD_v2.2_ldscores.tgz
gwas_summary_stats_url: https://zenodo.org/record/7768714/files/sumstats.tgz
encode_annotation_url: https://hgdownload.soe.ucsc.edu/goldenPath/hg19/database/wgEncodeAwgSegmentationCombinedGm12878.txt.gz
anno_fields: {genes:[[4, gene, self, str]],
              cds: [[4, cds, self, str]],
              gerp: [[5, gerp, self, num]],
              phastcons: [[6, phastcons, self, num]],
              phylop: [[6, phylop, self, num]],
              recomb: [[5, recomb, self, num]],
              bstat: [[4, B, self, num]],
              gnomad: [[ID, gnomad_ID, self, str],
                       [InbreedingCoeff, gnomad_InbreedingCoeff, self, str],
                       [AF_AFR, gnomad_af_afr, self, str],
                       [AF_AMR, gnomad_af_amr, self, str],
                       [AF_ASJ, gnomad_af_asj, self, str],
                       [AF_EAS, gnomad_af_eas, self, str],
                       [AF_FIN, gnomad_af_fin, self, str],
                       [AF_NFE, gnomad_af_NFE, self, str],
                       [AF_OTH, gnomad_af_oth, self, str],
                       [HOM_AFR, gnomad_hom_afr, self, str],
                       [HOM_AMR, gnomad_hom_amr, self, str],
                       [HOM_ASJ, gnomad_hom_asj, self, str],
                       [HOM_EAS, gnomad_hom_eas, self, str],
                       [HOM_FIN, gnomad_hom_fin, self, str],
                       [HOM_NFE, gnomad_hom_nfe, self, str],
                       [HOM_OTH, gnomad_hom_oth, self, str],
                       [STAR_AC, gnomad_ac_del, self, str],
                       [STAR_Hom, gnomad_del_hom, self, str],
                       [CSQ, gnomad_ensembl_vep, self, str],
                       [lcr, gnomad_lcr, self, str],
                       [segdup, gnomad_segdup, self, str]],
              clinvar: [[ALLELEID, clinvar_ID, self, str],
                        [CLNDN, clinvar_dn, self, str],
                        [CLNDNINCL, clinvar_dnincl, self, str],
                        [CLNDISDB, clinvar_disdb, self, str],
                        [CLNSIG, clinvar_sig, self, str],
                        [CLNSIGCONF, clinvar_sigconf, self, str],
                        [GENEINFO, clinvar_gene, self, str],
                        [MC, clinvar_mc, self, str],
                        [ORIGIN, clinvar_origin, self, str],
                        [RS, clinvar_dbSNP, self, str]],
              encode: [[4, reg, self, str]],
              ancestral: [[4, ancestral, self, str]],
              boosting_complete_eur: [[4, boosting_complete_eur, self, num]],
              boosting_complete_eur_recent: [[4, boosting_complete_eur_recent, self, num]],
              boosting_complete_eur_ancient: [[4, boosting_complete_eur_ancient, self, num]],
              boosting_incomplete_eur: [[4, boosting_incomplete_eur, self, num]],
              boosting_incomplete_eur_recent: [[4, boosting_incomplete_eur_recent, self, num]],
              boosting_incomplete_eur_ancient: [[4, boosting_incomplete_eur_ancient, self, num]],
              boosting_complete_afr: [[4, boosting_complete_afr, self, num]],
              boosting_complete_afr_recent: [[4, boosting_complete_afr_recent, self, num]],
              boosting_complete_afr_ancient: [[4, boosting_complete_afr_ancient, self, num]],
              boosting_incomplete_afr: [[4, boosting_incomplete_afr, self, num]],
              boosting_incomplete_afr_recent: [[4, boosting_incomplete_afr_recent, self, num]],
              boosting_incomplete_afr_ancient: [[4, boosting_incomplete_afr_ancient, self, num]],
              boosting_complete_eas: [[4, boosting_complete_eas, self, num]],
              boosting_complete_eas_recent: [[4, boosting_complete_eas_recent, self, num]],
              boosting_complete_eas_ancient: [[4, boosting_complete_eas_ancient, self, num]],
              boosting_incomplete_eas: [[4, boosting_incomplete_eas, self, num]],
              boosting_incomplete_eas_recent: [[4, boosting_incomplete_eas_recent, self, num]],
              boosting_incomplete_eas_ancient: [[4, boosting_incomplete_eas_ancient, self, num]],
              pi: [[5, pi, self, num]]}

# Species to use to identify CpG-islands
# Chimp, bonobo, and rhesus
species: [panTro6, ponAbe3, rheMac10]
# species: [panTro2, ponAbe2, rheMac2]

# Download links for archaic genomes
archaic_genomes_mpg_base_url: http://ftp.eva.mpg.de/neandertal/Vindija/
archaic_genomes_mpg_base_url_chagyrskaya: http://ftp.eva.mpg.de/neandertal/Chagyrskaya/
archaic_genomes_mpg_base_url_altai_old: http://ftp.eva.mpg.de/neandertal/altai/
archaic_genomes_mpg_url_filter_bed_altai_old: https://bioinf.eva.mpg.de/altai_minimal_filters/AltaiNea.map35_50.MQ30.Cov.indels.TRF.bed.bgz

# will predict introgressed segments using all of these archaic genomes
archaic_genomes: [Altai, Vindija33.19, Chagyrskaya, Denisova,]
# will mask segments predicted using these genomes if they overlap with Denisovan segments predicted in Africans
neanderthal_genomes: [Vindija33.19]
denisovan_genome: Denisova

# 1KG population codes + African-Americans (AA) identified in target data (must be last element in list)
populations: [YRI, ESN, MSL, GWD, LWK, CDX, CHB, CHS, KHV, JPT, CEU, GBR, IBS, FIN, TSI, AOUAFR, AOUEUR, AOUNA, AA]

# mapping of 1KG/HGDP populations to super-populations
pop_superpop_mapping: {CDX: EAS, CEU: EUR, CHB: EAS,
                       CHS: EAS, ESN: AFR, FIN: EUR, GBR: EUR,
                       GWD: AFR, IBS: EUR, JPT: EAS, KHV: EAS, LWK: AFR,
                       MSL: AFR, TSI: EUR, YRI: AFR, AOUAFR: AFR, AOUEUR: EUR, AOUNA: EAS, AA: AMR}

hgdp_pima_samples: [HGDP01041, HGDP01053, HGDP01058, HGDP01060, HGDP01057, HGDP01059, HGDP01037, HGDP01056, HGDP01043, HGDP01050, HGDP01055, HGDP01047, HGDP01044]
hgdp_mayan_samples: [HGDP00872, HGDP00877, HGDP00858, HGDP00860, HGDP00865, HGDP00869, HGDP00871, HGDP00876, HGDP00864, HGDP00857, HGDP00854, HGDP00859, HGDP00861, HGDP00873, HGDP00856, HGDP00863, HGDP00868, HGDP00870, HGDP00875, HGDP00862, HGDP00855]

# Binary paths
#ibdmix_directory: /storage/home/hcoda1/3/apfennig3/IBDmix/build/src/
ibdmix_directory: /home/jupyter/workspaces/neanderthalintrogressionlandscapeinafricanamericans/IBDmix/build/src/
#bcftools_path: /storage/home/hcoda1/3/apfennig3/bcftools/bcftools
bcftools_path: /home/jupyter/workspaces/neanderthalintrogressionlandscapeinafricanamericans/bcftools-1.19/bcftools
#bedtools_path: /storage/home/hcoda1/3/apfennig3/bedtools2/bin/bedtools
bedtools_path: /home/jupyter/workspaces/neanderthalintrogressionlandscapeinafricanamericans/bedtools2/bin/bedtools
bwa_path: bwa
#flare_path: /storage/home/hcoda1/3/apfennig3/flare/flare.jar
flare_path: /home/jupyter/workspaces/neanderthalintrogressionlandscapeinafricanamericans/flare.jar
ensembl_path: /storage/home/hcoda1/3/apfennig3/ensembl/
#rye_path: /storage/home/hcoda1/3/apfennig3/rye/rye.R
rye_path: /home/jupyter/workspaces/neanderthalintrogressionlandscapeinafricanamericans/rye/rye.R
simulations_path_base: simulations/

# data paths
data_path: data/
ibdmix_genotypes_path: ibdmix_genotypes/
results_path: results50kb_w_AOU/
ldsc_path: LDSC_analysis/ #cannot be ldsc
mask_path: masks/
whole_genome_alignments_path: whole_genome_alignments/
reference_path: reference/
seqbility_tmp: seqbility_splits/
merged_datasets_path: merged_datasets/
flare_output_path: flare/
genetic_map_path: hapmap_genetic_map/
human_ancestral_sequence_path: human_ancestral_sequence/
tmp_dir: /home/jupyter/workspaces/neanderthalintrogressionlandscapeinafricanamericans/introgression_african_americans
#tmp_dir: /storage/home/hcoda1/3/apfennig3/scratch/pre_all_of_us_10_03_2023/introgression_african_americans_testing

# Filters applied during merging of datasets
maf: 0.001
geno: 0.05

# Rye parameters
#K: 9 # defined by the number of groups in the pop2group.txt file
K: 7
M: 20 # number of PCs for Rye

# ancestry proportions for identifying African-American individuals
min_afr_component: 0.5
max_afr_component: 0.9
min_eur_component: 0.1
max_eur_component: 0.9
min_afr_eur_component_combined: 0.95

#IBDmix parameters
minimum_length: 50000
lod_threshold: 4.0
archaic_error_rate: 0.01
max_modern_error_rate: 0.002
modern_error_proportion: 2
min_minor_allele_count: 1
windowsize: 50000 # tile genome into bins of this size and determine frequency of introgession/local ancestry in each bin
stepsize: 10000
minimum_length_selected: 50000

simulation_replicates: 10

# hypothesis testing
alpha: 0.05 # significance level
min_expectation: 1 # Minimum number of expected introgressed haplotypes overlapping a window to be considered
bootstrap_reps: 100 # number of bootstraps for control segments


# introgression deserts
max_masked: 0.5
stride: 100000
window_sizes: [8000000, 9000000, 10000000, 11000000, 12000000, 13000000, 14000000, 15000000]

# computing resources
mem_gb_cpu: 16

#tsinfer + tsdata parameters
generation_time: 29 # in years
mutation_rate: 1.25e-8
arg_dir: ancestral_recombination_graphs/
effective_population_size: 10000

# iDAT scores
n_sites_idat: 10000 # number of random sites to compute iDAT score at for genome-wide scan
windowsize_idat: 20000000 # window size for which to compute average iDAT scores
stepsize_idat: 1000000 # step size to move window with
dist_step_size: 10000 # step size with which to move away from a reference point when computing DAT scores
min_cov_dat: 0.1
